#!/bin/bash
#
# ARG_OPTIONAL_BOOLEAN([hdmi],[],[tvservice on],[on])
# ARG_OPTIONAL_BOOLEAN([usb_ethernet],[],[USB and Ethernet on],[on])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.8.1 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info
# Generated online by https://argbash.io/generate


die()
{
  local _ret=$2
  test -n "$_ret" || _ret=1
  test "$_PRINT_HELP" = yes && print_help >&2
  echo "$1" >&2
  exit ${_ret}
}


begins_with_short_option()
{
  local first_option all_short_options=''
  first_option="${1:0:1}"
  test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_hdmi="on"
_arg_usb_ethernet="on"


print_help()
{
  printf 'Usage: %s [--(no-)hdmi] [--(no-)usb_ethernet]\n' "$0"
  printf '\t%s\n' "--hdmi, --no-hdmi: tvservice on (on by default)"
  printf '\t%s\n' "--usb_ethernet, --no-usb_ethernet: USB and Ethernet on (on by default)"
}


parse_commandline()
{
  while test $# -gt 0
  do
    _key="$1"
    case "$_key" in
      --no-hdmi|--hdmi)
        _arg_hdmi="on"
        test "${1:0:5}" = "--no-" && _arg_hdmi="off"
        ;;
      --no-usb_ethernet|--usb_ethernet)
        _arg_usb_ethernet="on"
        test "${1:0:5}" = "--no-" && _arg_usb_ethernet="off"
        ;;
      *)
        _PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
        ;;
    esac
    shift
  done
}

parse_commandline "$@"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

# Turn off USB/ethernet (for security & power saving)
if [[ "$usb_ethernet" == "off" ]]; then
  buspower="0"
else
  buspower="1"
fi
echo "Turning USB/ethernet $_arg_usb"
echo "${buspower}" | sudo tee /sys/devices/platform/soc/3f980000.usb/buspower >/dev/null

# Turn off HDMI
if [[ "$_arg_hdmi" == "off" ]]; then
  sudo tvservice --off
else
  sudo tvservice -p
fi

# Turn off swap.
sudo dphys-swapfile swapoff && sudo dphys-swapfile uninstall && sudo update-rc.d dphys-swapfile remove

bash autostart.sh

# ] <-- needed because of Argbash